# Generated by Django 3.2.9 on 2021-12-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_alter_doc_reg_info_docimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='healthcareDepartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('deptName', models.CharField(max_length=100, unique=True)),
                ('deptDescription', models.TextField()),
            ],
        ),
    ]
