# Generated by Django 3.2.9 on 2021-12-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0005_healthcaredepartments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='healthcaresInfo',
            new_name='healthcareCenter',
        ),
        migrations.RenameModel(
            old_name='healthcareDepartments',
            new_name='healthcareDepartment',
        ),
    ]
