# Generated by Django 3.2.9 on 2021-12-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0006_auto_20211210_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcaredepartment',
            name='deptRemarks',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
