# Generated by Django 3.2.9 on 2021-12-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=100)),
                ('patientNID', models.IntegerField()),
                ('patientDOB', models.DateField()),
                ('patientPhone', models.CharField(max_length=20)),
                ('patientEmail', models.CharField(max_length=50)),
                ('patientPassword', models.TextField()),
                ('patientImage', models.ImageField(upload_to='patientsUploadedImage')),
            ],
        ),
        migrations.DeleteModel(
            name='patients',
        ),
    ]
