# Generated by Django 3.2.9 on 2022-01-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patientsinfo_patientimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='chiefComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.IntegerField()),
                ('visitingDate', models.IntegerField()),
                ('complain', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='currentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.IntegerField()),
                ('visitingDate', models.IntegerField()),
                ('bloodPressure', models.CharField(max_length=10)),
                ('temperature', models.CharField(max_length=10)),
                ('pulse', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.IntegerField()),
                ('visitingDate', models.IntegerField()),
                ('diagnosis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.IntegerField()),
                ('visitingDate', models.IntegerField()),
                ('instruction', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.IntegerField()),
                ('visitingDate', models.IntegerField()),
                ('medicineName', models.CharField(max_length=100)),
                ('dose1', models.CharField(max_length=10)),
                ('dose2', models.CharField(max_length=10)),
                ('dose3', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='patientDOB',
            field=models.IntegerField(),
        ),
    ]
