# Generated by Django 3.2.9 on 2022-01-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20220108_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chiefcomplain',
            name='patientId',
        ),
        migrations.RemoveField(
            model_name='currentstatus',
            name='patientId',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='patientId',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='patientId',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='patientId',
        ),
        migrations.AddField(
            model_name='chiefcomplain',
            name='patientEmail',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='currentstatus',
            name='patientEmail',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patientEmail',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='instruction',
            name='patientEmail',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='patientEmail',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
