# Generated by Django 3.2.9 on 2021-12-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctorsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docName', models.CharField(max_length=100)),
                ('docNID', models.IntegerField()),
                ('docDOB', models.DateField()),
                ('docHospital', models.CharField(max_length=100)),
                ('docDepartment', models.CharField(max_length=100)),
                ('docEID', models.CharField(max_length=100)),
                ('docPhone', models.CharField(max_length=20)),
                ('docEmail', models.CharField(max_length=50)),
                ('docPassword', models.TextField()),
                ('docImage', models.ImageField(upload_to='doctorsUploadedImage')),
            ],
        ),
    ]
