# Generated by Django 3.2.9 on 2021-12-05 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctorsInfo',
        ),
    ]
